language: java

services:
  - docker

before_install:
  - docker build -t shdkej/tomcat_mypage .
  - docker run -d -p 127.0.0.1:8080:8080 shdkej/tomcat_mypage
  - docker ps -a

script:
  - echo "test"
