name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file board/pom.xml

    - name: Heroku install java plugin
      env: 
        HEROKU_API_KEY: ${{ secrets.herokuapi }}
      run: heroku plugins:install java
    - name: Heroku deploy app
      env:
        HEROKU_API_KEY: ${{ secrets.herokuapi }}
      run: heroku war:deploy gvm.war --app what-was-that --webapp-runner 8.5.50.0
